version: '3'

services:
  abibliadigital:
    build: ./docker-api
    command: [ "bash", "/usr/src/api/start.sh" ]
    ports:
      - "3000:3000"
    expose:
      - "3000"
    container_name: abibliadigital
    environment:
      - MONGODB_URI=mongodb://abibliadigital-mongo/abibliadigital
      - NODE_ENV=development
      - SECRET_KEY=19B2AFFC3B287A4E41FA7C1158A8A
      - REDIS_URL=redis://abibliadigital-redis
    volumes:
      - ../abibliadigital:/usr/src/api
    depends_on:
      - abibliadigital-mongo
      - abibliadigital-redis

  abibliadigital-mongo:
    build: ./docker-mongo
    container_name: abibliadigital-mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ../mongo-abibliadigital/db/data:/data/db
      - ../mongo-abibliadigital/db/log:/var/log/mongodb

  abibliadigital-redis:
    image: redis:alpine
    container_name: abibliadigital-redis
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
    volumes:
      - ../redis-data:/var/lib/redis

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=abibliadigital-mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - abibliadigital-mongo

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:abibliadigital-redis:6379
    depends_on:
      - abibliadigital-redis
